#!/bin/sh
# Calculate misfits of a suite of exhaustive search receiver functions in a
# specified directory.
# G. Helffrich/U. Bristol 1 Aug. 2006
#
# Emits pipe to generate list of file names without creating potentially large
# file patterns (glob strings), fiters out non-synthetic file names.

dir=${1:-none} ; shift
[ $dir = none ] && { echo **$0: No synthetics directory given ; exit 1 ; }
pars="$*"
ls -f $dir | 
   egrep '\.rfr$' |
   awk 'BEGIN{dir="'"${dir}"'"}{printf "%s%s\n",dir,$1}' |
   ./rfmisfit ${pars}
