#!/bin/sh
#  Make a record section of RF synthetics in a slowness range
m=/tmp/sp6-mod rng='4 8.75 0.5'
[ -f $m ] || sh makemodel > $m ; /bin/rm -f ${m}.sac.m
# [ -f $m ] || cat modeltest > $m ; /bin/rm -f ${m}.sac.m
pvals=`echo $rng | awk '{for(d=$1; d<$2+0.5*$3; d+=$3) print d}'`
for s in ${pvals} ; do
   echo $m | rfksyn -gen zrt -p $s s/deg -sps 20 -sph
   for c in z r t; do
      mv -f ${m}_sp.$c ${m}_sp${s}.$c
   done
   echo "m mtrf file ${m}_sp${s} comps r t z phase P" >> ${m}.sac.m
done
